# Generated by Django 5.1 on 2024-08-27 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Dosagem e horário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('😀', '😀 Feliz'), ('😐', '😐 Indiferente'), ('😞', '😞 Triste')], max_length=1, verbose_name='Humor')),
                ('content', models.TextField(verbose_name='Descreva o seu dia')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('remedios', models.ManyToManyField(related_name='entries', to='entries.remedio')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
