# Generated by Django 5.1 on 2024-08-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='horas',
            field=models.CharField(default='0', max_length=2, verbose_name='Quantas horas de Sono'),
        ),
        migrations.AddField(
            model_name='entry',
            name='informe',
            field=models.TextField(default='', verbose_name='Descreva o seu sono'),
        ),
        migrations.AddField(
            model_name='entry',
            name='sono',
            field=models.CharField(choices=[('😴 Bom', '😴 Bom'), ('🥱\tInsônia', '🥱 Insônia'), ('😫 Ruim', '😫 Ruim')], default='😴 Bom', max_length=100, verbose_name='Qualidade do Sono'),
        ),
    ]
