# Generated by Django 5.1 on 2024-08-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_horas_alter_entry_title_sonoregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SonoRegistro',
        ),
    ]
