# Generated by Django 5.1 on 2024-08-29 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_compra_compromisso_consumoagua_prioridade_tarefa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisso',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consumoagua',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prioridade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tarefacasa',
            name='user',
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pequeno_almoco', models.CharField(blank=True, max_length=255)),
                ('almoco', models.CharField(blank=True, max_length=255)),
                ('jantar', models.CharField(blank=True, max_length=255)),
                ('prioridades', models.TextField(blank=True)),
                ('compromissos', models.TextField(blank=True)),
                ('tarefas', models.TextField(blank=True)),
                ('coisas_para_comprar', models.TextField(blank=True)),
                ('limpar_a_casa', models.TextField(blank=True)),
                ('lema', models.CharField(blank=True, max_length=255)),
                ('anotacoes', models.TextField(blank=True)),
                ('copos_agua', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Compromisso',
        ),
        migrations.DeleteModel(
            name='ConsumoAgua',
        ),
        migrations.DeleteModel(
            name='Prioridade',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.DeleteModel(
            name='TarefaCasa',
        ),
    ]
