# Generated by Django 5.1 on 2024-09-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_planner_agua1_planner_agua2_planner_agua3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='agua1',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='agua2',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='agua3',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='agua4',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='agua5',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='agua6',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='copos_agua',
        ),
        migrations.CreateModel(
            name='CopoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebido', models.BooleanField(default=False)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copos_agua', to='entries.planner')),
            ],
        ),
    ]
