# Generated by Django 5.1 on 2024-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_remove_planner_agua1_remove_planner_agua2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='copos_agua',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CopoAgua',
        ),
    ]
