# Generated by Django 5.1 on 2024-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_planner_copos_agua_delete_copoagua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='descricao',
            field=models.TextField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome e Dosagem'),
        ),
    ]
