# Generated by Django 5.1 on 2024-09-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_alter_remedio_descricao_alter_remedio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(choices=[('😀', '😀 Feliz'), ('😐', '😐 Indiferente'), ('😞', '😞 Triste'), ('😡', '😡 Bravo'), ('😫', '😫 Cansado'), ('😤', '😤 Estressado')], default='😴 Bom', max_length=1, verbose_name='Humor'),
        ),
    ]
