# Generated by Django 5.1 on 2024-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='descricao',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
