# Generated by Django 5.1 on 2024-11-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_alter_remedio_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='compromissos',
            new_name='compromissos1',
        ),
        migrations.AddField(
            model_name='planner',
            name='compromissos2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='compromissos3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='compromissos4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='compromissos5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='compromissos6',
            field=models.TextField(blank=True),
        ),
    ]
